spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
  jpa:
    open-in-view: true
    properties.hibernate:
      show_sql: true
      format_sql: true
  mvc:
    path match:
      matching-strategy: ant_path_matcher
