spring:
  datasource:
    url: jdbc:postgresql://auth-database:5432/auth_db
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
    topics:
      topic-email-notification: ${TOPIC_EMAIL_NOTIFICATION}

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  validity:
    access-token: 60
    refresh-token: 60

remote:
  api-clients:
    user-api:
      baseUrl: http://user-service:8080/api/v1/users/
      retry:
        maxAttempts: 3
        durationInSeconds: 2

maxmind:
  geoip:
    country-db: GeoLite2-Country.mmdb